#!/usr/bin/env python3
"""Regenerate src/pygments-lexers.js: every lexer alias minted will accept.

minted 3 does not use whatever Pygments is on PATH: its `latexminted` loads a
copy bundled with TeX Live (scripts/minted/pygments-*.whl). That copy decides
which `\\begin{minted}{<lang>}` compile and which stop the document, so the
list is taken from it. Re-run when TeX Live updates minted's Pygments:

    python3 scripts/pygments-lexers.py [path/to/pygments-*.whl]
"""
import glob, os, sys, textwrap

if len(sys.argv) > 1:
    wheel = sys.argv[1]
else:
    found = sorted(glob.glob('/usr/local/texlive/*/texmf-dist/scripts/minted/pygments-*.whl'))
    if not found:
        sys.exit('no TeX Live minted Pygments wheel found; pass its path')
    wheel = found[-1]

sys.path.insert(0, wheel)
import pygments
from pygments.lexers import get_all_lexers

aliases = sorted({alias.lower() for _, names, _, _ in get_all_lexers() for alias in names})
body = textwrap.fill(' '.join(aliases), width=76, break_long_words=False, break_on_hyphens=False)
lines = '\n'.join(f"\t'{line} '" for line in body.split('\n'))
lines = lines.replace("\n", "\n\t+ ", ).replace("\t+ \t", "\t+ ")

out = f"""// GENERATED by scripts/pygments-lexers.py — do not edit by hand.
// Pygments {pygments.__version__}, from {os.path.basename(wheel)}: the copy TeX Live's minted
// (latexminted) bundles and uses, whatever Pygments is on PATH. Every lexer
// alias minted accepts as `\\begin{{minted}}{{<lang>}}` ({len(aliases)}); Pygments matches
// them case-insensitively. Re-run the script when TeX Live updates minted.

export const PYGMENTS_VERSION = '{pygments.__version__}';

export const PYGMENTS_LEXERS = new Set((
{lines}
).trim().split(' '));
"""
target = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'pygments-lexers.js')
with open(target, 'w') as f:
    f.write(out)
print(f'wrote {os.path.normpath(target)}: Pygments {pygments.__version__}, {len(aliases)} aliases')
